# Generated by Django 3.1.7 on 2021-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
