# Generated by Django 3.1.7 on 2021-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210523_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
